---
# see http://molecule.readthedocs.io/en/stable-1.9/usage.html
language: python

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - vagrant
      - ruby
      - ruby-bundler

install:
  - pip install -r requirements.txt
  - bundle install

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
