---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint tasks/*
  flake8
platforms:
  - name: centos
    image: centos:7
  - name: debian
    image: debian:stretch
  - name: ubuntu
    image: ubuntu:xenial
  - name: arch
    image: archlinux/base:latest
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
